### ISSUE TITLE
Steps desynchronization in tv mode

### ISSUE THREAD

**Issue by Johell1NS** [retronx-team/stepmania-nx#10]
I noticed that some songs, if played in TV mode, have unsynchronized steps. While others behave in the same way both in portable mode and on the TV ... What can this depend on?
I also performed the "Calibrate audio sync" procedure, but the problem persists.

**Comment by p-sam** [comment]
I'm not sure what can possibly happen related to stepmania and/or your switch but only while docked. So, I'm going to close this as it looks more like general support than a project issue. First thing that comes to mind is the TV, so i'd check that.

**Comment by Johell1NS** [comment]
If it depended on the tv, then the out of sync should happen with all the songs, instead it only happens with some songs.

**Comment by p-sam** [comment]
I can help you troubleshoot further, but you first need to point me to the songs that exhibit the behavior you're referring to. In the case of particular songs being slower than others, it can def happen with heavy scripted ones. Do you use sys-clk by any chance ?
