### ISSUE TITLE
Does not work under AMS 0.19.0

### ISSUE THREAD

**Issue by toomymon** [retronx-team/stepmania-nx#11]
Hi team,

This seems to crash under atmosphere 0.19.0. Perhaps due to some code changes as listed here? Is it possible to update Stepmania to work with the new AMS? Much appreciated and thanks.

```

sm, boot2, pgl were updated to reflect the latest official behaviors.
Please Note: 12.0.0 added a new protocol for IPC ("tipc"), which has been freshly reimplemented in its entirety.
It is possible there may be as of yet unfound issues; if there are, please send the appropriate crash reports to SciresM (SciresM#0524 on discord).
Homebrew which uses atmosphere extensions (including the mitm API) will need to be re-compiled in order to function on 0.19.0.
I apologize for this, but it's unavoidable for technical reasons. If you're affected by this and mad about it, please contact SciresM to complain.

```

https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.19.0

**Comment by p-sam** [comment]
Yes, it's on my todo-list, the same happened to a few ports that were compiled on now-old versions of libnx, I'm probably going to tackle Stepmania next (and might just need a recompile)

**Comment by toomymon** [comment]
Awesome to hear. Appreciate this a lot. Stepmania has been my go to for indoor cardio.

**Comment by p-sam** [comment]
You can find a recompiled version on the release page that should fix the crashes
