### ISSUE TITLE
Crashes when starting to play simfile

### ISSUE THREAD

**Issue by pupperrika** [retronx-team/stepmania-nx#13]
Hello, I'm running the recompiled 5.1-nx2 8ab10aad 20210503 release on 12.1.0|AMS M.19.5|S (thru https://github.com/Team-Neptune/DeepSea) and when I select a song to play I receive the "The software was closed because an error occurred." message (shortly after showing the "EVENT mode" screen with the track name and duration on the older theme (it crashes on the newer theme too)). It also crashes when loading the jukebox mode or trying to test a song in the edit mode. Oddly, the audio/video sync setting function that automatically calculates a new delay based on your inputs doesn't crash and I'm able to "play" it despite it being very similar to the modes which are crashing. I'm receiving the crash when testing with the included song "Goin' Under" by NegaRen, but it is also crashing in this way with every song I've tried. I tried changing a few graphics, display, and theme settings to see if it would help, but so far it always crashes. I've included a crash log and the associated image. Thank you, and please let me know if I can provide any more info. I can try to compile the debug build and test with that if it would help.

(As a side note, I also did not have the switch controller keymaps from the README when I first started Stepmania and needed to plug in a keyboard to interact with the menus.)

![01630901523_0100a1c00359c000](https://user-images.githubusercontent.com/90211086/132248355-19aa1e3f-49e0-4648-8691-90dd45c203a8.jpg)

[01630901523_0100a1c00359c000.log](https://github.com/retronx-team/stepmania-nx/files/7117268/01630901523_0100a1c00359c000.log)

**Comment by p-sam** [comment]
Have you tried correctly copying the files again?

**Comment by pupperrika** [comment]
I hadn't, but I just tried extracting to a new folder (`stepmania 2`) under `/switch` and am getting the same results

**Comment by p-sam** [comment]
I would try to copy the release with a different computer and run the archive bit fix, since I had a few cases already of crashes reported to me because of files missing

**Comment by pupperrika** [comment]
Good thinking, I had been using OSX to install but just tried extracting it under Windows and the controller configuration is there when I start up the game and the tracks play perfectly. I had run the archive bit fix before, so I didn't think the OSX extraction would have been an issue. Thanks very much for your quick response and sorry to bother you!

**Comment by p-sam** [comment]
@pupperrika np, OSX seems to be a common denominator in file copy issues, which is why I always ask first for another try, closing the issue now
