### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by VampireSavior** [retronx-team/stepmania-nx#16]
Using 13.2.1/AMS 1.2.6 the game gives the standard "Software was closed due to an issue" screen and crashes. Tried with download from github page and HB store.

**Comment by VampireSavior** [comment]
Install was corrupted, fixed

**Comment by tinyNinjja** [comment]
Using 15.0FW with Atmosphere 1.4.0.
Attempting to run Stepmania both from github and HB store and like previous comment it does not load.  On mine, it starts and compiles songs but then goes to a black screen.  Switch does not freeze, you can still push Home to return.

Thoughts?  Will there be another recompile?
Thanks.

**Comment by p-sam** [comment]
I suspect either a faulty SD or a bad copy/install, try again from the start. I'm closing this since it's still running fine on latest fw and ams

**Comment by tinyNinjja** [comment]
Thank you, I found from previous issue threads that you shouldn't be opening this in HBM applet mode.  I opened through holding R over any game and it works now!

Apologies for asking here, not positive if I should open a new issue or if there is a different place to ask questions.  I'm new to github so feel free to direct me to post somewhere else.  Is there a way to have Stepmania show up as any other game title?  Or are there any plans for this in the future?  My experience is limited, after running Tinfoil from the HBM it automatically puts a Tinfoil "game" in the normal path for opening apps/games.

Thanks again for any guidance.

**Comment by p-sam** [comment]
I see, that's right you should open most homebrew over games if you can help it. As for the other thing, you did good not creating another issue, since what you described involves piracy stuff, I can't help you with that

**Comment by tinyNinjja** [comment]
My apologies.  I think I need to educate myself on what is considered piracy.  I thought for sure this was not since it is open-source homebrew content.  If you have any direct links or articles I can read to understand please let me know.

Thank you for your help!
