### ISSUE TITLE
load up

### ISSUE THREAD

**Issue by pito4evr** [retronx-team/stepmania-nx#3]
the game crashes when loading up for the first time. it crashes at the point where it loads most_played13-16.crs

**Comment by pito4evr** [comment]
I tried that and it still crashed. However I did get it to work by making an nsp out of the nro

**Comment by p-sam** [comment]
*facepalm*

**Comment by m4xw** [comment]
Hahahahahahaha

**Comment by p-sam** [comment]
Yea this is quite the ironic situation
