### ISSUE TITLE
Keymaps empty by default

### ISSUE THREAD

**Issue by Sereni** [retronx-team/stepmania-nx#4]
When I launch stepmania, it has no keymaps, which makes it impossible to proceed past the loading screen. The Save folder created after launch contains an empty Keymaps.ini. If I manually place some mappings there, everything works.

**Comment by p-sam** [comment]
The defaults controls are as shown in the README on first launch, else as you said you would not be able to use it, try again

**Comment by Sereni** [comment]
Hey p-sam,

Thanks — but the keys mentioned in the readme did not work for me on launch, not until I edited Keymaps.ini manually. Interestingly, after I manually created a mapping and got to the options menu, the mappings there were pre-filled with the values from the readme. However, the buttons worked according to what I had in Keymaps.ini (and if there was nothing there, nothing worked). Do you know why this may be happening?

**Comment by p-sam** [comment]
No, i've never had that happening, my guess is your Save folder was not empty and just removing the Keymaps is not enough

**Comment by p-sam** [comment]
There is also another thing though, I also had people forgetting they had another joycon connected or a pro controller, and didn't understand why the attached joycon didn't work.

**Comment by Sereni** [comment]
Hm, I'm sure I only have two joycons, because that's all I own. What is strange is my configure key menu shows a keyboard, mouse, and eight (!) switch controllers recognized. Perhaps that has something to do with it :)
I'm going to close this and update if I find something more specific, hopefully the discussion will help someone having the same issue.
