### ISSUE TITLE
Dancemats compatibility? 

### ISSUE THREAD

**Issue by bedouille85** [retronx-team/stepmania-nx#7]
I have an USB dancemat and à ps1 dance mat with USB Converter tool. I dont succeed to make thèm work. Are they compatible?

**Comment by p-sam** [comment]
If you don't succeed in registering inputs in the input settings screen, that probably means those dancemats aren't compatible. I'd say the most likely dancemats to be compatible are the ones that are gamecube compatible (with the right adapter), and the ones that act like a keyboard.
