### ISSUE TITLE
The game does not appear in the list

### ISSUE THREAD

**Issue by Johell1NS** [retronx-team/stepmania-nx#8]
I have inserted the "stepmania" folder inside the "switch" folder on the root of the SD card, but when I enter in HBL the game does not appear, what can I do?

**Comment by p-sam** [comment]
Try copying the files again, it would seem that the stepmania.nro file is missing

**Comment by Johell1NS** [comment]
I have already tried several times. The file is present, but it does not appear in the list.
I have firmware 11.0.1 | AMS M.17.0 | S
hbmenu v3.4.0
nx-hbloader v2.4.0

**Comment by p-sam** [comment]
Have you tried this while copying? https://switch.homebrew.guide/troubleshooting.html
Else idk what's going on

**Comment by Johell1NS** [comment]
I solved using windows instead of mac for copying files, i don't know why but using mac the game was not appearing

**Comment by p-sam** [comment]
Archive bit it was then, it's explained in the link I sent you
